AddCSLuaFile("cl_init.lua")
AddCSLuaFile("shared.lua")
include("shared.lua")
 
function ENT:Initialize()
self:SetModel("models/props/cs_office/computer_monitor.mdl")
self:PhysicsInit(SOLID_VPHYSICS)
self:SetMoveType(MOVETYPE_VPHYSICS)
self:SetSolid(SOLID_VPHYSICS)  
self:SetUseType(SIMPLE_USE)
local phys = self:GetPhysicsObject()
if phys and phys:IsValid() then phys:Wake() end

	self:SetNWString(TranslationMedicMod.LUNG,"mri_empy")
	self:SetNWString(TranslationMedicMod.LIVER,"mri_empy")
	self:SetNWString(TranslationMedicMod.KIDNEY,"mri_empy")
	self:SetNWString(TranslationMedicMod.HEART,"mri_empy")
	self:SetNWString(TranslationMedicMod.SPLEEN,"mri_empy")
	self:SetNWString(TranslationMedicMod.AORTA,"mri_empy")
	util.AddNetworkString(self:EntIndex().."MRIMenuOpen")
	util.AddNetworkString(self:EntIndex().."MRIDestroy")
	net.Receive(self:EntIndex().."MRIDestroy", function(act, ply)
		self:SetNWString(TranslationMedicMod.LUNG,"mri_empy")
		self:SetNWString(TranslationMedicMod.LIVER,"mri_empy")
		self:SetNWString(TranslationMedicMod.KIDNEY,"mri_empy")
		self:SetNWString(TranslationMedicMod.HEART,"mri_empy")
		self:SetNWString(TranslationMedicMod.SPLEEN,"mri_empy")
		self:SetNWString(TranslationMedicMod.AORTA,"mri_empy")
		self:EmitSound("ambient/machines/keyboard"..math.random(1,6).."_clicks.wav")
		ply:SendLua("local tab = {Color(170, 170, 170), TranslationMedicMod.Youhavedestroyedyourdata } chat.AddText(unpack(tab))")
	end)
end

function ENT:Use(ply)
	self:EmitSound("ambient/machines/keyboard"..math.random(1,6).."_clicks.wav")
	net.Start(self:EntIndex().."MRIMenuOpen")
	net.WriteEntity(self)
	net.Send(ply)
end